app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin,current_user
from . import login_manager

from . import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_secure = db.Column(db.String(255))

    
    @property
    def password(self):
            raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
            self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
            return check_password_hash(self.pass_secure,password)
    def __repr__(self):
        return f'{self.username}'


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))

    def __repr__(self):
        return f'User {self.name}'



class BlogCategory(db.Model):

    __tablename__ = 'categories'

    # table columns
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    description = db.Column(db.String(255))

    # save blog
    def save_category(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_categories(cls):
        categories = BlogCategory.query.all()
        return categories


#blog class
class Blog(db.Model):
    """ List of blogs in each category """

    __tablename__ = 'blogs'

    id = db.Column(db.Integer,primary_key = True)
    content = db.Column(db.String)
    category_id = db.Column(db.Integer, db.ForeignKey("categories.id"))
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    comment = db.relationship("Comments", backref="blog", lazy = "dynamic")
    



    def save_blog(self):
        ''' Save the blog '''
        db.session.add(self)
        db.session.commit()

    @classmethod
    def clear_blog(cls):
        Blog.all_blog.clear()

    # display blog

    def get_blog(id):
        blog = Blog.query.filter_by(category_id=id).all()
        return blog


# comments
class Comments(db.Model):
    '''User comment model for each blog '''

    __tablename__ = 'comments'

    # add columns
    id = db.Column(db. Integer, primary_key=True)
    opinion = db.Column(db.String(255))
#     time_posted = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    blog_id = db.Column(db.Integer, db.ForeignKey("blogs.id"))


    def save_comment(self):
        '''
        Save the Comments/comments per blog
        '''
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(self, id):
        comment = Comments.query.order_by(
            Comments.time_posted.desc()).filter_by(blog_id=id).all()
        return comment

class Quotes:
    def __init__(self,author,quote):
        self.author = author
        self.quote = quote

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required
from wtforms.validators import DataRequired





class BlogForm(FlaskForm):
     title = StringField('Title', validators=[DataRequired()])
     content = TextAreaField('Content',validators=[DataRequired()])
     submit = SubmitField('Blog')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
bootstrap = Bootstrap()
db = SQLAlchemy()
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
mail = Mail()


# def create_app(config_name):
#     #....
#     #Initializing Flask Extensions
#     bootstrap.init_app(app)
#     db.init_app(app)
#     login_manager.init_app(app)

photos = UploadSet('photos',IMAGES)
def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    app.config.from_object(config_options[config_name])
    mail.init_app(app)
    
     # configure UploadSet
    configure_uploads(app,photos)

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    
    # Will add the views and forms

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views, errors

app/main/views.py
from flask import render_template, request, redirect, url_for, abort
from . import main
from .. import db,photos
from app.requests import GetQuotes
from flask_login import login_required,current_user
from .forms import BlogForm

#display categories on the landing page
@main.route('/')
def index():
    """ View root page function that returns index page """
    
    quotes = GetQuotes()
    print(quotes)
    title = 'Home- Welcome'
    return render_template('index.html', title = title,quotes = quotes)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/comment', methods = ['GET','POST'])
def comment():
    form =BlogForm()
    if form.validate_on_submit():
      blog = Blog(title = form.title.data, category =form.category.data, content = form.content.data, author = form.author.data,upvote = 0,downvote = 0,user_id=current_user.id)
      blog.save_blog()
    return render_template('comment.html',form=form)

# @main.route('/comments/<int:blog_id>/comment',methods=['POST','GET'])
# @login_required
# def comment(blog_id):
#     form = CommentsForm()
#     blog = Blog.query.filter_by(id = blog_id).first()
#     user = current_user.username
#     if form.validate_on_submit():
#         comment = Comment(content = form.comment.data,user_id = current_user.id,blog_id = blog.id)
#         db.session.add(comment)
#         db.session.commit()
#         return redirect(url_for('./comment'),blog_id=blog_id))
#     return render_template('comments.html', form = form,blog=blog,blog_id=blog_id,user=user)

@main.route('/view', methods = ['GET','POST'])
def view():

    return render_template('view.html')

@main.route('/about', methods = ['GET','POST'])
def about():
    
    return render_template('about.html')

@main.route('/profile', methods = ['GET','POST'])
def profile():
    
    return render_template('profile.html')

app/templates/about.html
{% extends 'base.html'%}


{% block styles%}
{{ super() }}
<link rel="stylesheet" href="../static/css/styles.css">
<link href="https://fonts.googleapis.com/css?family=Notable&display=swap" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="container-fluid">
<div class="container">
    <div class="row">
      <h1>About</h1>
      <p>This is a personal blogging site where you can share your opinions about my personal blogs and comment  on them 
      <p>It also has inspiratioal qupotes to help us encounter our daily activitues well</p>    
      <p>November 21,2019</p>
    </div>
    
</div>
  {%endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html' %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
{% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Home- Welcomeg to the Blog Website</title>
    {% endif %}
</head>

<body>
    {% block content %} {% endblock %}

    {% block navbar %} {% include 'navbar.html' %} {% endblock %}
    
</body>

</html>

app/templates/comment.html
{% extends 'base.html'%}


{% block styles%}
{{ super() }}
<link rel="stylesheet" href="../static/css/styles.css">
{% endblock %}
{% block content %}
<div class="container-fluid">
  <div class="container">
    <div class="card">
      <form method="POST" action="">
        <fieldset class="form-group">
          <legend class="bottom mb-4">New Post</legend>
          <div class="form-group">
            {{form.title.label(class="form-control-label")}}
            {% if form.title.errors%}
            {{ form.title(class="form-control form-control-lg is-invalid") }}
            <div class="feedback">
              {% for error in form.title.errors %}
              <span>{{ error}}</span>
              {% endfor %}
            </div>
            {% else%}
            {{ form.title(class="form-control form-control-lg")}}
            {% endif %}
          </div>
          <div class="form-group">
            {{form.content.label(class="form-control-label")}}
            {% if form.content.errors%} <div class="form-group <div class=" form-group">
              {{ form.submit(class='btn btn-outline-info') }}
            </div>">
            {{ form.submit(class='btn btn-outline-info') }}
          </div>
          {{ form.content(class="form-control form-control-lg is-invalid") }}
          <div class="feedback">
            {% for error in form.content.errors %}
            <span>{{ error}}</span>
            {% endfor %} <div class="form-group">
              {{ form.submit(class='btn btn-outline-info') }}
            </div>
          </div>
          {% else%}
          {{ form.content(class="form-control form-control-lg")}}
          {% endif %}


          <div class="form-group">
            {{ form.submit(class='btn btn-outline-info') }}
          </div>
    </div>
  </div>
  </fieldset>

  </form>

  {% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/fourOwfour.css')}}">

{% endblock %}
{% block content %}
<div class="container-fluid">
<div class="row">
    <div class="col-md-6 col-md-offset-4">
        <div class="error-template">
            <h1>
                Oops!</h1>
            <h2>
                404 Not Found</h2>
            <div class="error-details">
                Sorry, an error has occured, Requested page not found!
            </div>
            <div class="error-actions">
            </br>
                <a href="/" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-home"></span>
                    Navigate Home </a>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block styles%}
{{ super() }}

<link rel="stylesheet" href="../static/css/styles.css">
 <link href="https://fonts.googleapis.com/css?family=Notable&display=swap" rel="stylesheet">
{% endblock %}
{% block content %}

<body>

  <h1>GET BLOGGING </h1>
  

  <br>
  <br>
  <br>
  <div class="card">
    <div class="card-hoverable">
        <div class="col-md-4 text-center">
            <h3>{{quotes.quote}}</h3>
            <h5>{{quotes.author}}</h5>
        </div>
    </div>
  
</body>
{% endblock %}

app/templates/navbar.html
<link rel="stylesheet" href="../static/css/styles.css">
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid bg-success">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle = "collapse" data-target = ".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
              <a class="navbar-brand" href="/" style=" font-size:30px"><div class="btn">HOME</div> </a>
  
      </div>
        <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right">
                  
                  <li><a href="{{url_for('main.comment')}}"><div class="btn btn-primary">Comment</div></a></li>
                  <li><a href="{{url_for('main.about')}}"><div class="btn btn-primary">About</div></a></li>

      

                 {% if current_user.is_authenticated %}
  
                     <li><a href="/">{{current_user.username.capitalize()}}</a></li>
                     <li><a href="{{url_for('auth.logout')}}"><div class="btn btn-primary">Sign out</div></a></li>
  
                 {%else%}
                     <li><a href="{{url_for('auth.login')}}"><div class="btn btn-primary">Sign in</div></a></li>
                     <li><a href="{{url_for('main.profile')}}"><div class="btn btn-primary">Profile</div></a></li>

  
                 {%endif%}
              </ul>
         </div>
  
    </div>
  </div>

app/templates/profile.html
<!DOCTYPE html>
<html>
<head>
    <meta charset ="utf-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>About me</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

    <header>
    
        <div class="name ">
            Thông
        </div>

        <div class="ava">
            <img src="https://api.sololearn.com/Uploads/Avatars/868188.jpg" alt="avatar" />
    

    </header>
    <div class="content">
        <aside class="info ">
            <div class="box">
                <p class="title">
                    <i class="fa fa-info-circle"></i>Contact
                </p>


                <p class="padd-top">
                    <i class="fa fa-birthday-cake"></i>
                    2-2-2222
                </p>

                <p>
                    <i class="fa fa-phone"></i>
                    0123456789
                </p>            

                <p>
                    <i  class="fa fa-envelope"></i>
                    qwerty@gmail.com
                </p>                

                <p>
                    <i class="fa fa-home"></i>
                    123 lorem ipsum, 
                </p>                

            </div> 

            <div class="box">

                <p class="title" >
                    <i  class="fa fa-asterisk"></i>
                    Skill
                </p>

                <p class="padd-top">HTML, CSS</p>
                <div class="skill">

                    <div class="skill-right r1"></div>
                </div>

                <p>JavaScript/jQuery</p>
                <div class="skill">

                    <div class="skill-right r2"></div>
                </div>

                <p>PHP, SQL</p>
                <div class="skill">

                    <div class="skill-right r3"></div>
                </div>
            </div>  

        </aside>


         
            </div>

        </section>

    </div>
    <footer>    </footer>
</body>
</html>